### ISSUE TITLE
AbsolutePoseSacProblem has no member named inlier_distances_to_model_

### ISSUE THREAD

**Issue by Bwaki** [laurentkneip/opengv#70]
Hello,

I am actually trying to build the package aslam_cv_geometric_vision who depends on opengv with catkin build but i don't know why i got an error. It said that :  
> AbsolutePoseSacProblem has no member named inlier_distances_to_model_

I am working on Ubuntu 16.04 with Ros Kinetic and i have install opengv following this tutorial [https://laurentkneip.github.io/opengv/page_installation.html](url)

PS complete error output : 

`Errors     << aslam_cv_geometric_vision:make /home/joe/catkin_ws/logs/aslam_cv_geometric_vision/build.make.002.log
In file included 

from /home/joe/catkin_ws/src/aslam_cv2/aslam_cv_cameras/include/aslam/cameras/camera.h:11:0,

from /home/joe/catkin_ws/src/aslam_cv2/aslam_cv_cameras/include/aslam/cameras/camera-pinhole.h:4,

from /home/joe/catkin_ws/src/aslam_cv2/aslam_cv_geometric_vision/src/pnp-pose-estimator.cc:3:
/home/joe/catkin_ws/src/aslam_cv2/aslam_cv_geometric_vision/src/pnp-pose-estimator.cc: In member function ‘bool aslam::geometric_vision::PnpPoseEstimator::absoluteMultiPoseRansac(const Matrix2Xd&, const std::vector&, const Matrix3Xd&, double, int, aslam::NCamera::ConstPtr, aslam::Transformation*, std::vector, std::vector, int*)’:

/home/joe/catkin_ws/src/aslam_cv2/aslam_cv_geometric_vision/src/pnp-pose-estimator.cc:252:43: error: ‘class opengv::sac::Ransacopengv::sac_problems::absolute_pose::AbsolutePoseSacProblem’ has no member named ‘inlier_distances_to_model_’
CHECK_EQ(ransac.inliers_.size(), ransac.inlier_distances_to_model_.size());
^
/home/joe/catkin_ws/devel/.private/glog_catkin/include/glog/logging.h:746:44: note: in definition of macro ‘CHECK_OP_LOG’
google::GetReferenceableValue(val2),
^
/home/joe/catkin_ws/devel/.private/glog_catkin/include/glog/logging.h:788:30: note: in expansion of macro ‘CHECK_OP’
#define CHECK_EQ(val1, val2) CHECK_OP(EQ, ==, val1, val2)
^
/home/joe/catkin_ws/src/aslam_cv2/aslam_cv_geometric_vision/src/pnp-pose-estimator.cc:252:3: note: in expansion of macro ‘CHECK_EQ’
CHECK_EQ(ransac.inliers.size(), ransac.inlier_distances_to_model_.size());
^
/home/joe/catkin_ws/src/aslam_cv2/aslam_cv_geometric_vision/src/pnp-pose-estimator.cc:270:39: error: ‘class opengv::sac::Ransacopengv::sac_problems::absolute_pose::AbsolutePoseSacProblem’ has no member named ‘inlier_distances_to_model_’
*inlier_distances_to_model = ransac.inlier_distances_to_model_;
^
make[2]: *** [CMakeFiles/aslam_cv_geometric_vision.dir/src/pnp-pose-estimator.cc.o] Error 1
make[1]: *** [CMakeFiles/aslam_cv_geometric_vision.dir/all] Error 2
make: *** [all] Error 2
cd /home/joe/catkin_ws/build/aslam_cv_geometric_vision; catkin build --get-env aslam_cv_geometric_vision | catkin env -si /usr/bin/make --jobserver-fds=6,7 -j; cd -`

If anyone have an idea where did it came from ?

Thanks you in advance,

Clement

**Comment by Bwaki** [comment]
So for everyone who have the same problem the solution for me was to 'catkin clean' my workspace
and to take the package opengv from 'https://github.com/ethz-asl/opengv' git clone it into my ~/catkin_ws/src and 'catkin build' my WS with that catkin recognize opengv and build him (i don't know why but it works fine for me)
